apiVersion: v1
kind: Service
metadata:
  name: nbu-web
spec:
  selector:
    app: nbu-web
  type: NodePort   
  ports:
    - protocol: TCP
      port: 8000           
      targetPort: 8000     
      nodePort: 30007      
